name: EDS Branch Publish

on:
  - push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/parts/cache/
      - name: Install packages
        working-directory: ./packages/eds
        run: |
          pnpm install
      - name: Build
        working-directory: ./packages/eds
        run: |
          pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/eds/dist
          publish_branch: hlx/${{ github.ref_name }}
