name: EDS Branch Cleanup

on:
  - delete

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'delete' && !startsWith(github.event.ref, 'hlx/') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          git push origin :hlx/${{ github.event.ref }}
